apiVersion: v1
kind: Service
metadata:
  name: sonatype-nexus-service
  namespace: sonatype-nexus
  labels:
    name: sonatype-nexus
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30081
  selector:
    app: sonatype-nexus
